# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PageBlock import PageBlock

class Ui_QWidget(object):
    def setupUi(self, QWidget):
        QWidget.setObjectName("QWidget")
        QWidget.resize(934, 542)
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        QWidget.setFont(font)
        QWidget.setStyleSheet("QWidget{\n"
"    font: 14pt \"幼圆\",\"Microsoft YaHei\";\n"
"}\n"
"\n"
"QComboBox {\n"
"    width: 30px;\n"
"    height: 40px;\n"
"    font-size: 30px;\n"
"    border: 0px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    border: 1px solid black;\n"
"}")
        self.table = QtWidgets.QTableWidget(QWidget)
        self.table.setGeometry(QtCore.QRect(20, 370, 461, 151))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.single_step = QtWidgets.QPushButton(QWidget)
        self.single_step.setGeometry(QtCore.QRect(500, 470, 121, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.single_step.setFont(font)
        self.single_step.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 163, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(76, 191, 0);\n"
"}")
        self.single_step.setObjectName("single_step")
        self.consecu_step = QtWidgets.QPushButton(QWidget)
        self.consecu_step.setGeometry(QtCore.QRect(640, 470, 121, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.consecu_step.setFont(font)
        self.consecu_step.setStyleSheet("QPushButton {background-color: rgb(3, 110, 202);}\n"
"QPushButton:hover {background-color: rgb(2, 130, 234);}")
        self.consecu_step.setCheckable(True)
        self.consecu_step.setObjectName("consecu_step")
        self.reset_all = QtWidgets.QPushButton(QWidget)
        self.reset_all.setGeometry(QtCore.QRect(780, 470, 121, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reset_all.setFont(font)
        self.reset_all.setStyleSheet("QPushButton {background-color: rgb(36, 161, 153);}\n"
"QPushButton:hover {background-color: rgb(42, 190, 180);}")
        self.reset_all.setObjectName("reset_all")
        self.label = QtWidgets.QLabel(QWidget)
        self.label.setGeometry(QtCore.QRect(20, 320, 221, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pf_count = QtWidgets.QLabel(QWidget)
        self.pf_count.setGeometry(QtCore.QRect(500, 370, 161, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pf_count.setFont(font)
        self.pf_count.setObjectName("pf_count")
        self.pf_rate = QtWidgets.QLabel(QWidget)
        self.pf_rate.setGeometry(QtCore.QRect(500, 410, 181, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pf_rate.setFont(font)
        self.pf_rate.setObjectName("pf_rate")
        self.page_label_1 = QtWidgets.QLabel(QWidget)
        self.page_label_1.setGeometry(QtCore.QRect(20, 200, 141, 43))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.page_label_1.setFont(font)
        self.page_label_1.setObjectName("page_label_1")
        self.page_label_2 = QtWidgets.QLabel(QWidget)
        self.page_label_2.setGeometry(QtCore.QRect(190, 200, 141, 43))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.page_label_2.setFont(font)
        self.page_label_2.setObjectName("page_label_2")
        self.page_label_3 = QtWidgets.QLabel(QWidget)
        self.page_label_3.setGeometry(QtCore.QRect(360, 200, 141, 43))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.page_label_3.setFont(font)
        self.page_label_3.setObjectName("page_label_3")
        self.page_2 = PageBlock(QWidget)
        self.page_2.setGeometry(QtCore.QRect(190, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setProperty("value", 100)
        self.page_2.setProperty("textVisible", False)
        self.page_2.setObjectName("page_2")
        self.page_label_4 = QtWidgets.QLabel(QWidget)
        self.page_label_4.setGeometry(QtCore.QRect(530, 200, 141, 43))
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.page_label_4.setFont(font)
        self.page_label_4.setObjectName("page_label_4")
        self.page_3 = PageBlock(QWidget)
        self.page_3.setGeometry(QtCore.QRect(360, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_3.sizePolicy().hasHeightForWidth())
        self.page_3.setSizePolicy(sizePolicy)
        self.page_3.setProperty("value", 100)
        self.page_3.setProperty("textVisible", False)
        self.page_3.setObjectName("page_3")
        self.page_1 = PageBlock(QWidget)
        self.page_1.setGeometry(QtCore.QRect(20, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_1.sizePolicy().hasHeightForWidth())
        self.page_1.setSizePolicy(sizePolicy)
        self.page_1.setProperty("value", 100)
        self.page_1.setProperty("textVisible", False)
        self.page_1.setObjectName("page_1")
        self.page_4 = PageBlock(QWidget)
        self.page_4.setGeometry(QtCore.QRect(530, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_4.sizePolicy().hasHeightForWidth())
        self.page_4.setSizePolicy(sizePolicy)
        self.page_4.setProperty("value", 100)
        self.page_4.setProperty("textVisible", False)
        self.page_4.setObjectName("page_4")
        self.label_11 = QtWidgets.QLabel(QWidget)
        self.label_11.setGeometry(QtCore.QRect(390, 80, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("font: 25 28pt \"Microsoft YaHei UI\";")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(QWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font: 25pt;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(QWidget)
        self.label_8.setGeometry(QtCore.QRect(620, 20, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(QWidget)
        self.label_12.setGeometry(QtCore.QRect(530, 80, 41, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet("font: 25 28pt \"Microsoft YaHei UI\";")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(QWidget)
        self.label_9.setGeometry(QtCore.QRect(770, 20, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.sequence = QtWidgets.QComboBox(QWidget)
        self.sequence.setGeometry(QtCore.QRect(780, 81, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.sequence.setFont(font)
        self.sequence.setStyleSheet("font: 25 28pt \"Microsoft YaHei UI\";")
        self.sequence.setObjectName("sequence")
        self.sequence.addItem("")
        self.sequence.addItem("")
        self.sequence.addItem("")
        self.algo = QtWidgets.QComboBox(QWidget)
        self.algo.setGeometry(QtCore.QRect(620, 80, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.algo.setFont(font)
        self.algo.setStyleSheet("font: 25 28pt \"Microsoft YaHei UI\";")
        self.algo.setObjectName("algo")
        self.algo.addItem("")
        self.algo.addItem("")
        self.label_4 = QtWidgets.QLabel(QWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 171, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(QWidget)
        self.label_10.setGeometry(QtCore.QRect(220, 82, 91, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet("font: 25 28pt \"Microsoft YaHei UI\";")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(QWidget)
        self.label_5.setGeometry(QtCore.QRect(210, 20, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(QWidget)
        self.label_6.setGeometry(QtCore.QRect(340, 20, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆,Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(QWidget)
        self.label_7.setGeometry(QtCore.QRect(470, 20, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(QWidget)
        self.line.setGeometry(QtCore.QRect(20, 180, 191, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(QWidget)
        self.line_2.setGeometry(QtCore.QRect(20, 340, 215, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.temp_3 = PageBlock(QWidget)
        self.temp_3.setGeometry(QtCore.QRect(360, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_3.sizePolicy().hasHeightForWidth())
        self.temp_3.setSizePolicy(sizePolicy)
        self.temp_3.setProperty("value", 100)
        self.temp_3.setProperty("textVisible", False)
        self.temp_3.setObjectName("temp_3")
        self.temp_1 = PageBlock(QWidget)
        self.temp_1.setGeometry(QtCore.QRect(20, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_1.sizePolicy().hasHeightForWidth())
        self.temp_1.setSizePolicy(sizePolicy)
        self.temp_1.setProperty("value", 100)
        self.temp_1.setProperty("textVisible", False)
        self.temp_1.setObjectName("temp_1")
        self.temp_2 = PageBlock(QWidget)
        self.temp_2.setGeometry(QtCore.QRect(190, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_2.sizePolicy().hasHeightForWidth())
        self.temp_2.setSizePolicy(sizePolicy)
        self.temp_2.setProperty("value", 100)
        self.temp_2.setProperty("textVisible", False)
        self.temp_2.setObjectName("temp_2")
        self.temp_4 = PageBlock(QWidget)
        self.temp_4.setGeometry(QtCore.QRect(530, 250, 152, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_4.sizePolicy().hasHeightForWidth())
        self.temp_4.setSizePolicy(sizePolicy)
        self.temp_4.setProperty("value", 100)
        self.temp_4.setProperty("textVisible", False)
        self.temp_4.setObjectName("temp_4")
        self.label_13 = QtWidgets.QLabel(QWidget)
        self.label_13.setGeometry(QtCore.QRect(750, 510, 171, 31))
        self.label_13.setStyleSheet("font: 10pt;")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "操作系统之内存管理"))
        self.single_step.setText(_translate("QWidget", "单步执行"))
        self.consecu_step.setText(_translate("QWidget", "连续执行"))
        self.reset_all.setText(_translate("QWidget", "重置"))
        self.label.setText(_translate("QWidget", "请求调页信息与结果"))
        self.label_2.setText(_translate("QWidget", "内存中的页面图示"))
        self.pf_count.setText(_translate("QWidget", "缺页次数: 000"))
        self.pf_rate.setText(_translate("QWidget", "缺页率: 00.00%"))
        self.page_label_1.setText(_translate("QWidget", "PAGE x"))
        self.page_label_2.setText(_translate("QWidget", "PAGE x"))
        self.page_label_3.setText(_translate("QWidget", "PAGE x"))
        self.page_label_4.setText(_translate("QWidget", "PAGE x"))
        self.label_11.setText(_translate("QWidget", "10"))
        self.label_3.setText(_translate("QWidget", "操作系统"))
        self.label_8.setText(_translate("QWidget", "页面置换算法"))
        self.label_12.setText(_translate("QWidget", "4"))
        self.label_9.setText(_translate("QWidget", "指令执行顺序"))
        self.sequence.setItemText(0, _translate("QWidget", "SKIP"))
        self.sequence.setItemText(1, _translate("QWidget", "顺序"))
        self.sequence.setItemText(2, _translate("QWidget", "随机"))
        self.algo.setItemText(0, _translate("QWidget", "FIFO"))
        self.algo.setItemText(1, _translate("QWidget", "LRU"))
        self.label_4.setText(_translate("QWidget", "内存的请求调页存储方式演示"))
        self.label_10.setText(_translate("QWidget", "320"))
        self.label_5.setText(_translate("QWidget", "作业指令总数"))
        self.label_6.setText(_translate("QWidget", "每页存放指令数"))
        self.label_7.setText(_translate("QWidget", "作业占用内存页数"))
        self.label_13.setText(_translate("QWidget", "1853434 谭梓煊 制作"))

